name: ddd_notes
description: A notes application using Firebase following a domain-driven-design pattern

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.6
  get_it: ^4.0.2
  injectable: ^0.4.0
  cloud_firestore: ^0.13.5
  flushbar: ^1.10.4
  uuid: ^2.0.4

dev_dependencies:
  build_runner:
  freezed: ^0.10.8
  injectable_generator: ^0.4.0
  lint: ^1.2.0

flutter:
  uses-material-design: true
