name: ddd_notes
description: A notes application using Firebase following a domain-driven-design pattern

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  dartz: ^0.9.1
  get_it: ^4.0.2
  flushbar: ^1.10.4
  kt_dart: ^0.7.0+1
  auto_route: ^0.5.0
  flutter_bloc: ^4.0.0
  injectable: ^0.4.0+1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.6
  freezed_annotation: ^0.7.1

dev_dependencies:
  build_runner:
  freezed: ^0.10.9
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.5.0
  lint: ^1.2.0

flutter:
  uses-material-design: true
