name: ddd_notes
description: A notes application using Firebase following a domain-driven-design pattern

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.2.0
  dartz: ^0.9.1
  get_it: ^4.0.2
  rxdart: ^0.24.1
  flushbar: ^1.10.4
  kt_dart: ^0.7.0+1
  logger: ^0.9.1
  auto_route: ^0.6.4
  flutter_bloc: ^5.0.1
  injectable: ^0.4.0+1
  google_fonts: ^1.1.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  freezed_annotation: ^0.11.0

dev_dependencies:
  build_runner:
  lint: ^1.2.0
  freezed: ^0.11.4
  json_serializable: ^3.3.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.6.4

flutter:
  uses-material-design: true
